// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { RollupV6$Type } from "./RollupV6";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["RollupV6"]: RollupV6$Type;
    ["contracts/rollup/RollupV6.sol:RollupV6"]: RollupV6$Type;
  }
}
