// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { RollupV5$Type } from "./RollupV5";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["RollupV5"]: RollupV5$Type;
    ["contracts/rollup/RollupV5.sol:RollupV5"]: RollupV5$Type;
  }
}
