// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { BurnToAddressRouter$Type } from "./BurnToAddressRouter";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["BurnToAddressRouter"]: BurnToAddressRouter$Type;
    ["contracts/router/BurnToAddress.sol:BurnToAddressRouter"]: BurnToAddressRouter$Type;
  }
}
