// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface BurnToAddressRouter$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "BurnToAddressRouter",
  "sourceName": "contracts/router/BurnToAddress.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "usdcAddr",
          "type": "address"
        },
        {
          "internalType": "address",
          "name": "to",
          "type": "address"
        },
        {
          "internalType": "uint256",
          "name": "value",
          "type": "uint256"
        }
      ],
      "name": "burnToAddress",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    }
  ],
  "bytecode": "0x608080604052346100165761012e908161001c8239f35b600080fdfe6080806040526004361015601257600080fd5b600090813560e01c6365fb480c14602857600080fd5b3460cf57606036600319011260cf576001600160a01b03826004358281169081900360cf5760243592831680930360cf578380926064926020956323b872dd60e01b8452336004850152602484015260443560448401525af1801560ed57608d575080f35b60203d811160e7575b601f8101601f1916820167ffffffffffffffff81118382101760d35760209183916040528101031260cf57518015150360cc5780f35b80fd5b5080fd5b634e487b7160e01b84526041600452602484fd5b503d6096565b6040513d84823e3d90fdfea2646970667358221220a6eca7c04af637fb90f2095a6598db54c198078be587b0921d7a02a067ab868864736f6c63430008140033",
  "deployedBytecode": "0x6080806040526004361015601257600080fd5b600090813560e01c6365fb480c14602857600080fd5b3460cf57606036600319011260cf576001600160a01b03826004358281169081900360cf5760243592831680930360cf578380926064926020956323b872dd60e01b8452336004850152602484015260443560448401525af1801560ed57608d575080f35b60203d811160e7575b601f8101601f1916820167ffffffffffffffff81118382101760d35760209183916040528101031260cf57518015150360cc5780f35b80fd5b5080fd5b634e487b7160e01b84526041600452602484fd5b503d6096565b6040513d84823e3d90fdfea2646970667358221220a6eca7c04af637fb90f2095a6598db54c198078be587b0921d7a02a067ab868864736f6c63430008140033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "BurnToAddressRouter",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<BurnToAddressRouter$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/router/BurnToAddress.sol:BurnToAddressRouter",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<BurnToAddressRouter$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "BurnToAddressRouter",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<BurnToAddressRouter$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/router/BurnToAddress.sol:BurnToAddressRouter",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<BurnToAddressRouter$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "BurnToAddressRouter",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<BurnToAddressRouter$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/router/BurnToAddress.sol:BurnToAddressRouter",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<BurnToAddressRouter$Type["abi"]>>;
}
