// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { AcrossWithAuthorization$Type } from "./AcrossWithAuthorization";
import { IAcross$Type } from "./IAcross";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["AcrossWithAuthorization"]: AcrossWithAuthorization$Type;
    ["IAcross"]: IAcross$Type;
    ["contracts/AcrossWithAuthorization.sol:AcrossWithAuthorization"]: AcrossWithAuthorization$Type;
    ["contracts/AcrossWithAuthorization.sol:IAcross"]: IAcross$Type;
  }
}
