// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IAcross$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IAcross",
  "sourceName": "contracts/AcrossWithAuthorization.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "depositor",
          "type": "address"
        },
        {
          "internalType": "address",
          "name": "recipient",
          "type": "address"
        },
        {
          "internalType": "address",
          "name": "inputToken",
          "type": "address"
        },
        {
          "internalType": "address",
          "name": "outputToken",
          "type": "address"
        },
        {
          "internalType": "uint256",
          "name": "inputAmount",
          "type": "uint256"
        },
        {
          "internalType": "uint256",
          "name": "outputAmount",
          "type": "uint256"
        },
        {
          "internalType": "uint256",
          "name": "destinationChainId",
          "type": "uint256"
        },
        {
          "internalType": "address",
          "name": "exclusiveRelayer",
          "type": "address"
        },
        {
          "internalType": "uint32",
          "name": "quoteTimestamp",
          "type": "uint32"
        },
        {
          "internalType": "uint32",
          "name": "fillDeadline",
          "type": "uint32"
        },
        {
          "internalType": "uint32",
          "name": "exclusivityDeadline",
          "type": "uint32"
        },
        {
          "internalType": "bytes",
          "name": "message",
          "type": "bytes"
        }
      ],
      "name": "depositV3",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IAcross",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IAcross$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/AcrossWithAuthorization.sol:IAcross",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IAcross$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IAcross",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IAcross$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/AcrossWithAuthorization.sol:IAcross",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IAcross$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IAcross",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IAcross$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/AcrossWithAuthorization.sol:IAcross",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IAcross$Type["abi"]>>;
}
